### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by jeremysanders** [jeremysanders/pyemf3#2]
Hi @robmcmullen 

You're the original author of the pyemf package, aren't you? I'm just adding this issue because I've mostly succeeded in getting the package to work with Python3 (hence the rename to pyemf3). I've put my updated version here.

Can I clarify the licence of the package? Is it LGPL-2.0? Would you be happy if it were changed to be LGPL-2.0 or later? - this would make it more compatible with Qt.

Thanks

Jeremy

**Comment by robmcmullen** [comment]
Great, thanks for converting it to python 3 for modern use. it's totally fine with me to change it to LGPL-2.0 or later.

I'm a bit surprised that there's still a need for this now that SVG is well supported! I guess code always lives longer than you expect. :smile:

**Comment by jeremysanders** [comment]
Probably it's less relevant now, but people like to use it in my plotting program. I think many MS office versions don't support SVG.

Thanks very much for writing it, and agreeing to the licence change!
